### ISSUE TITLE
get-started-rollup build failed

### ISSUE THREAD

**Issue by but0n** [visgl/loaders.gl#1011]
yarn build result:

<details>

```
node_modules/@loaders.gl/core/dist/esm/lib/api/parse.js -> node_modules/@loaders.gl/core/dist/esm/lib/loader-utils/parse-with-worker.js -> node_modules/@loaders.gl/core/dist/esm/lib/api/parse.js
[!] Error: 'toArrayBuffer' is not exported by node-resolve:empty.js, imported by node_modules/@loaders.gl/core/dist/esm/javascript-utils/binary-utils.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@loaders.gl/core/dist/esm/javascript-utils/binary-utils.js (2:9)
1: import { assert } from '@loaders.gl/loader-utils';
2: import { toArrayBuffer as bufferToArrayBuffer } from '../node/utils/to-array-buffer.node';
            ^
3: export function toArrayBuffer(data) {
4:   if (bufferToArrayBuffer) {
Error: 'toArrayBuffer' is not exported by node-resolve:empty.js, imported by node_modules/@loaders.gl/core/dist/esm/javascript-utils/binary-utils.js
    at error (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at handleMissingExport (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:9725:28)
    at Module.traceVariable (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:10163:24)
    at ModuleScope.findVariable (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:8770:39)
    at FunctionScope.findVariable (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at Identifier$1.bind (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:4403:40)
    at IfStatement.bind (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at BlockStatement$1.bind (/Users/but0n/GitHub/get-started-rollup/node_modules/rollup/dist/shared/node-entry.js:3148:31)

error Command failed with exit code 1.
```

</details>

**Comment by but0n** [comment]
It can be build successfully on my own rollup setups, but I got an error from the browser's console shows `require is not defined` at this [line](https://github.com/visgl/loaders.gl/blob/5df6102f4c30a9984f9dd92a4c53aedae84deb08/modules/las/src/lib/laslaz-decoder.js#L8).

This file will contain two `import` statements at the beginning once compiled by babel, but rollup doesn't support this kind of mixing: https://github.com/rollup/rollup/issues/1058#issuecomment-254187433

**Comment by ibgreen** [comment]
Thanks for reporting, I can confirm the issue.

We don't use rollup on a regular basis, so we should also add a test case for this.
