### ISSUE TITLE
Tile Converter Error: No valid loader found data: "ÿØÿà", contentType: ""

### ISSUE THREAD

**Issue by dag18e** [visgl/loaders.gl#1969]
I've been getting this error while trying to use the tile converter. It has happened with both the docker image and the npm versions. The error is not unique to this layer, it has happened on many layers so far and I have yet to get one to fully convert.

I am pretty sure I installed correctly. I used the install instructions [here](https://loaders.gl/modules/tile-converter/docs/cli-reference/tile-converter). I feel like maybe I'm missing a dependency somewhere or something? I ran `--install-dependencies` so I'm not sure what else might be needed.

```
$ docker run visgl/tile-converter --name test --input-type I3S --tileset https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/Frankfurt2017_vi3s_18/SceneServer/layers/0
------------------------------------------------
Starting conversion of I3S
------------------------------------------------
Loading egm file...
Loading egm file completed!
Node conversion: 1
A 3D tile failed to load: undefined No valid loader found data: "ÿØÿà", contentType: ""
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'vertexCount' of null
    at Yh._addChildren (/loaders-bundle/converter.min.js:292:395198)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Yh.convert (/loaders-bundle/converter.min.js:292:394738)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I did get one to begin converting and then hit a roadblock that throws the same error.
```
docker run visgl/tile-converter --name test --input-type I3S --tileset https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0
------------------------------------------------
Starting conversion of I3S
------------------------------------------------
Loading egm file...
Loading egm file completed!
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/0
loaders.gl: i3s loader option 'i3s.fetch' not recognized.
loaders.gl: Top level loader option 'attributeName' not recognized.
loaders.gl: Top level loader option 'attributeType' not recognized.
/test/0.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/1
/test/1.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/2
/test/2.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/3
/test/3.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/4
/test/4.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/5
/test/5.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/6
/test/6.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/7
/test/7.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/8
/test/8.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/9
/test/9.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/10
/test/10.b3dm saved.
Node conversion: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/11
A 3D tile failed to load: https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/DevA_BuildingShells/SceneServer/layers/0/nodes/11 No valid loader found data: "ÿØÿà", contentType: ""
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'vertexCount' of null
    at Yh._addChildren (/loaders-bundle/converter.min.js:292:395198)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Yh.convert (/loaders-bundle/converter.min.js:292:394738)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dryabinin-actionengine** [comment]
@dag18e Hello! I think we already fixed this issue while development process. If you are using docker I will prepare beta docker image and notify you about that.

**Comment by dag18e** [comment]
That would be great, thank you!

**Comment by dryabinin-actionengine** [comment]
@dag18e I pushed **v3.1.0-beta-7** version of tile-converter to the [dockerhub](https://hub.docker.com/repository/docker/visgl/tile-converter). Please try to use it and let us know how it works.
