### ISSUE TITLE
Parse URL error for local file parsing 

### ISSUE THREAD

**Issue by kochizufan** [visgl/loaders.gl#2161]
Hi, is this bug?

Even the document says `load` function allow file name, actually it causes error.
Environment is 
* Node@18.0.0
* loader.gl@3.1.8 (core, las)
* OS: Occured in both Windows10 and WSL2
```
import {LASLoader} from "@loaders.gl/las";
import {load} from "@loaders.gl/core";

const main = async function() {
  const data = await load("/mnt/f/challenge/C_37EZ1.LAS", LASLoader, {});
  console.log(data);
};

main();
```
With such code, it causes error like:
```
node:internal/deps/undici/undici:6460
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from /mnt/f/challenge/C_37EZ1.LAS
    at new Request (node:internal/deps/undici/undici:6460:19)
    at Agent2.fetch (node:internal/deps/undici/undici:7157:29)
    ... 4 lines matching cause stack trace ...
    at Generator.invoke [as _invoke] (/mnt/f/challenge/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/mnt/f/challenge/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/mnt/f/challenge/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/mnt/f/challenge/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:372:5)
      at URL.onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:6458:25)
      at Agent2.fetch (node:internal/deps/undici/undici:7157:29)
      at Object.fetch (node:internal/deps/undici/undici:8060:22)
      at fetch (node:internal/bootstrap/pre_execution:194:25)
      at _callee$ (/mnt/f/challenge/node_modules/@loaders.gl/core/dist/es5/lib/fetch/fetch-file.js:42:20)
      at tryCatch (/mnt/f/challenge/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/mnt/f/challenge/node_modules/regenerator-runtime/runtime.js:294:22) {
    input: '/mnt/f/challenge/C_37EZ1.LAS',
    code: 'ERR_INVALID_URL'
  }
}
```

I tried several representations of file location, all are the same result.
* absolute path: (/mnt/f/challenge/C_37EZ1.LAS in WSL or F:\\challenge\\C_37EZ1.LAS in Windows)
* relative path: (./C_37EZ1.LAS in WSL or .\\C_37EZ1.LAS in Windows)
* file scheme: file:///f/challenge/C_37EZ1.LAS

In addition, in Node@16, there is another error:
```
/mnt/f/challenge/node_modules/@loaders.gl/core/dist/es5/lib/fetch/fetch-file.js:42
            return fetch(url, fetchOptions);
            ^

ReferenceError: fetch is not defined
    at _callee$ (/mnt/f/challenge/node_modules/@loaders.gl/core/dist/es5/lib/fetch/fetch-file.js:42:13)
    at tryCatch (/mnt/f/challenge/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/mnt/f/challenge/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/mnt/f/challenge/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/mnt/f/challenge/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/mnt/f/challenge/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /mnt/f/challenge/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /mnt/f/challenge/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at _fetchFile (/mnt/f/challenge/node_modules/@loaders.gl/core/dist/es5/lib/fetch/fetch-file.js:61:21)
```

Are these errors or expected behaviors?

**Comment by kylebarron** [comment]
> In addition, in Node@16, there is another error:

You may need to install the polyfills for working in Node: https://loaders.gl/docs/developer-guide/polyfills. Then at least `fetch` should be defined. That may also be related to support for reading a file, but I'm not sure.

**Comment by dandv** [comment]
Ran into the same issue with basically the vanilla JSON parsing from the [docs page](https://loaders.gl/modules/json/docs/api-reference/json-loader). adding `import '@loaders.gl/polyfills';` fixed the issue. Should that line be added to that example, or to examples in general?

**Comment by kochizufan** [comment]
Sorry for late response

Honestly speaking, I'm no longer need for this fix.
Not only no need, but also I already cannot access resources of this bug (Regarding my changing job).
Hence, I think if this don't occur in your local, this issue can be closed.
