### ISSUE TITLE
Issues with polyfills and vite

### ISSUE THREAD

**Issue by guy-otonomo** [visgl/loaders.gl#2379]
I'm trying to move an existing project from `CRA` to `vite`.
When running `vite build` the following exception is thrown to the console and build fails:
```
"atob" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/polyfills/dist/esm/node/file/file-reader.js".
file: /home/projects/vitejs-vite-1kcttf/node_modules/@loaders.gl/polyfills/dist/esm/node/file/file-reader.js:2:9
1: import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";
2: import { atob } from '../buffer/btoa.node';
            ^
3: export class FileReaderPolyfill {
error during build:
RollupError: "atob" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/polyfills/dist/esm/node/file/file-reader.js".
    at error (file://file:///home/projects/vitejs-vite-1kcttf/node_modules/rollup/dist/es/shared/node-entry.js:2130:30)
    at Module.error (file://file:///home/projects/vitejs-vite-1kcttf/node_modules/rollup/dist/es/shared/node-entry.js:13199:16)
```

Repro: https://stackblitz.com/edit/vitejs-vite-1kcttf?file=main.js
Tried with `@loaders.gl/polyfills@3.3.0`
Open the repro, and run in console `npm run build`.

Thanks

**Comment by ibgreen** [comment]
Hmm, yes this makes sense. It is the named import that causes the crash. 
- Could be addressed by `import * as BTOA from `...` technique with if statement or by providing a browser version of the file. 

polyfills module was mainly intended for use in Node.js but sometimes code needs to run in both places.

**Comment by VictorVelarde** [comment]
Hi @guy-otonomo did you find a simple way to deal with this issue?

**Comment by guy-otonomo** [comment]
@VictorVelarde unfortunately no. We use loaders.gl as a transient dependency of another project, and that one has its own issues with Vite. So for the time being we'll stick with Webpack.

**Comment by ibgreen** [comment]
Handling of polyfills has been completely refactored in 4.0, hopefully resolving any lingering issues.

**Comment by sebastian-schuler** [comment]
We're having similar issues after upgrading to Vite 5, using ``loaders.gl 4.0.4`` and ``vite 5.0.6``.

```
node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js (45:26) "requireFromFile" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js".
node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js (45:57) "requireFromFile" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js".
node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js (59:16) "requireFromString" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js".
node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js (59:42) "requireFromString" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js".
node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js (76:25) "readFileAsArrayBuffer" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js".
node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js (80:20) "readFileAsArrayBuffer" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js".
node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js (83:25) "readFileAsText" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js".
node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js (87:20) "readFileAsText" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/library-utils/library-utils.js".
node_modules/@loaders.gl/worker-utils/dist/lib/process-utils/child-process-proxy.js (50:42) "spawn" is not exported by "__vite-browser-external", imported by "node_modules/@loaders.gl/worker-utils/dist/lib/process-utils/child-process-proxy.js".
```

Is there a possible workaround for this? It was perfectly fine in Vite 4.
