### ISSUE TITLE
tile-converter unknown scheme

### ISSUE THREAD

**Issue by pyGisServer** [visgl/loaders.gl#2589]
I am trying to convert a collection of 3DTiles generated in DJI Terra to ".slpk" formats. The data set plays fine in Cesium ion, however when I run the loaders.gl conversion command I always get the same error failing to convert.

`C:\Users\pygisserver>npx tile-converter --input-type 3DTILES --tileset D:\PROJECTS\TEST\terra_b3dms\tileset.json --output D:\PROJECTS\TEST\loaders_slpk\TEST --name test --slpk`

```
Input tileset value: D:\PROJECTS\TEST\terra_b3dms\tileset.json
Modified tileset value: D:/PROJECTS/TEST/terra_b3dms/tileset.json
------------------------------------------------
Starting conversion of 3DTILES
------------------------------------------------
Loading egm file...
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async na (C:\Users\pygisserver\node_modules\@loaders.gl\tile-converter\dist\converter.min.js:125:15449)
    at async ci (C:\Users\pygisserver\node_modules\@loaders.gl\tile-converter\dist\converter.min.js:125:32844)
    at async $_.convert (C:\Users\pygisserver\node_modules\@loaders.gl\tile-converter\dist\converter.min.js:125:255735)
    at async eht (C:\Users\pygisserver\node_modules\@loaders.gl\tile-converter\dist\converter.min.js:125:294371)
    at async Zft (C:\Users\pygisserver\node_modules\@loaders.gl\tile-converter\dist\converter.min.js:125:292063) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:6893:35)
      at schemeFetch (node:internal/deps/undici/undici:11036:18)
      at node:internal/deps/undici/undici:10909:26
      at mainFetch (node:internal/deps/undici/undici:10926:11)
      at fetching (node:internal/deps/undici/undici:10883:7)
      at fetch2 (node:internal/deps/undici/undici:10761:20)
      at Object.fetch (node:internal/deps/undici/undici:11574:18)
      at fetch (node:internal/process/pre_execution:229:25)
      at na (C:\Users\pygisserver\node_modules\@loaders.gl\tile-converter\dist\converter.min.js:125:15455)
      at ci (C:\Users\pygisserver\node_modules\@loaders.gl\tile-converter\dist\converter.min.js:125:32850)
}

C:\Users\pygisserver>
```

**Comment by dsactionengine** [comment]
Hi @pyGisServer 
Could you please provide a bit more context?
- NodeJS version
- Tile-converter version (or commit number if you compiled from master)
- Your operating system and version

Is the dataset you are trying to convert available for the public so we can also test it? If so - please link it here so we could investigate the issue better.

**Comment by dsactionengine** [comment]
Hey @pyGisServer any updates?

**Comment by ibgreen** [comment]
Close due to lack of activity
